/**
 * Knowledge Management Types
 * Types for personal knowledge management system
 */

export interface JournalEntry {
  id: string;
  date: Date;
  type: JournalType;
  content: string;
  summary?: string;
  mood?: MoodLevel;
  tags: string[];
  linkedEntities: LinkedEntity[];
  insights: string[];
  metadata: JournalMetadata;
}

export type JournalType = 
  | 'daily'
  | 'reflection'
  | 'learning'
  | 'project'
  | 'meeting'
  | 'decision'
  | 'achievement';

export type MoodLevel = 'great' | 'good' | 'neutral' | 'stressed' | 'frustrated';

export interface LinkedEntity {
  type: 'person' | 'project' | 'concept' | 'file' | 'conversation';
  id: string;
  name: string;
  relevance: number;
}

export interface JournalMetadata {
  wordCount: number;
  readTime: number;
  autoGenerated: boolean;
  editedAt?: Date;
  conversationIds?: string[];
  toolsUsed?: string[];
}

export interface Insight {
  id: string;
  type: InsightType;
  title: string;
  content: string;
  confidence: number;
  source: InsightSource;
  tags: string[];
  actionable: boolean;
  suggestedActions?: string[];
  createdAt: Date;
  reviewedAt?: Date;
  dismissed: boolean;
}

export type InsightType =
  | 'pattern'
  | 'recommendation'
  | 'learning'
  | 'reminder'
  | 'connection'
  | 'summary';

export interface InsightSource {
  type: 'conversation' | 'journal' | 'behavior' | 'calendar' | 'external';
  ids: string[];
  timeRange?: { start: Date; end: Date };
}

export interface KnowledgeItem {
  id: string;
  type: KnowledgeType;
  title: string;
  content: string;
  summary?: string;
  confidence: number;
  source: string;
  tags: string[];
  relatedItems: string[];
  nextReview?: Date;
  reviewCount: number;
  lastReviewed?: Date;
  difficulty: number; // 0-1, used for spaced repetition
  createdAt: Date;
  updatedAt: Date;
}

export type KnowledgeType =
  | 'fact'
  | 'concept'
  | 'procedure'
  | 'preference'
  | 'skill'
  | 'vocabulary';

export interface ReviewSession {
  id: string;
  items: ReviewItem[];
  startTime: Date;
  endTime?: Date;
  completed: boolean;
  score?: number;
}

export interface ReviewItem {
  itemId: string;
  presented: boolean;
  recalled: boolean;
  responseTime?: number;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export interface SpacedRepetitionConfig {
  enabled: boolean;
  dailyLimit: number;
  minInterval: number; // hours
  maxInterval: number; // days
  easeFactor: number; // default 2.5
  intervals: number[]; // progression of intervals
}

export interface DailyDigest {
  date: Date;
  summary: string;
  highlights: string[];
  insights: Insight[];
  upcomingReviews: KnowledgeItem[];
  stats: {
    conversationCount: number;
    tasksCompleted: number;
    newKnowledge: number;
    reviewsCompleted: number;
  };
}

export const DEFAULT_SPACED_CONFIG: SpacedRepetitionConfig = {
  enabled: true,
  dailyLimit: 20,
  minInterval: 4, // 4 hours
  maxInterval: 365, // 1 year
  easeFactor: 2.5,
  intervals: [1, 3, 7, 14, 30, 60, 120, 365] // days
};
